public with sharing class AnimalLocator {
        public static String getAnimalNameById(integer i) {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://th-apex-http-callout.herokuapp.com/animals/id'+i);
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            // If the request is successful, parse the JSON response.
            if(response.getStatusCode() == 200) {
                // Deserializes the JSON string into collections of primitive data types.
                Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                // Cast the value in the 'animal' key as a string
                Map<String, Object> animal = (Map<String, Object>) result.get('animal');
                System.debug('Name: '+string.valueOf(animal.get('name')));
            } else {
                return null;
            }
        }
}